---
- name: Update package cache
  apt:
    update_cache: yes
  become: yes

- name: Install Python and curl
  apt:
    name:
      - python3
      - curl
    state: present
  become: yes

- name: Apply basic updates
  apt:
    upgrade: yes
  become: yes
